# .bash_profile (additions)
#
# Author: Mike McKerns (mmckerns @caltech and @uqfoundation)
# Copyright (c) 1997-2016 California Institute of Technology.
# Copyright (c) 2016-2023 The Uncertainty Quantification Foundation.
# License: 3-clause BSD.  The full license text is available at:
#  - https://github.com/uqfoundation/pox/blob/master/LICENSE

# Get standard aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# Activate the ssh-agent
if [ -f ~/.ssh_agent ]; then
	. ~/.ssh_agent
fi

# Get additional aliases and functions 
if [ -f ~/.pathosrc ]; then
	. ~/.pathosrc
fi

