# .bash_profile (additions)
#
# Author: Mike McKerns (mmckerns @caltech and @uqfoundation)
# Copyright (c) 1997-2014 California Institute of Technology.
# License: 3-clause BSD.  The full license text is available at:
#  - http://trac.mystic.cacr.caltech.edu/project/pathos/browser/pox/LICENSE

# Get standard aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# Activate the ssh-agent
if [ -f ~/.ssh_agent ]; then
	. ~/.ssh_agent
fi

# Get additional aliases and functions 
if [ -f ~/.pathosrc ]; then
	. ~/.pathosrc
fi

